#!/bin/bash

curl -s https://api.github.com/orgs/serpapi/repos?per_page=200 | ruby -rubygems -e 'require "json"; JSON.load(STDIN.read).each { |repo| %x[git clone #{repo["ssh_url"]}] if repo["ssh_url"].start_with?("git@github.com:serpapi/test-")}'